// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// SimpleTests - Use 'SimpleTestsParams' to pass parameters into this method.
        /// </summary>
        public void SimpleTests()
        {
            #region Variable Declarations
            WpfButton uIStartButton = this.UIMainWindowWindow.UIStartButton;
            WpfCheckBox uICheckBoxCheckBox = this.UIMainWindowWindow.UICheckBoxCheckBox;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
            ApplicationUnderTest uIMainWindowWindow = ApplicationUnderTest.Launch(this.SimpleTestsParams.UIMainWindowWindowExePath, this.SimpleTestsParams.UIMainWindowWindowAlternateExePath);

            // Click 'Start' button
            Mouse.Click(uIStartButton, new Point(52, 21));

            // Select 'CheckBox' check box
            uICheckBoxCheckBox.Checked = this.SimpleTestsParams.UICheckBoxCheckBoxChecked;

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(24, 34));
        }
        
        /// <summary>
        /// SimpleTests2 - Use 'SimpleTests2Params' to pass parameters into this method.
        /// </summary>
        public void SimpleTests2()
        {
            #region Variable Declarations
            WpfButton uIStartbuttonA = this.UIMainWindowWindow.UIStartbuttonA;
            WpfCheckBox uICheckBoxCheckBox = this.UIMainWindowWindow.UICheckBoxCheckBox;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
            ApplicationUnderTest uIMainWindowWindow = ApplicationUnderTest.Launch(this.SimpleTests2Params.UIMainWindowWindowExePath, this.SimpleTests2Params.UIMainWindowWindowAlternateExePath);

            // Click 'Start' button
            Mouse.Click(uIStartbuttonA, new Point(79, 10));

            // Select 'CheckBox' check box
            uICheckBoxCheckBox.Checked = this.SimpleTests2Params.UICheckBoxCheckBoxChecked;

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(13, 28));
        }
        
        #region Properties
        public virtual SimpleTestsParams SimpleTestsParams
        {
            get
            {
                if ((this.mSimpleTestsParams == null))
                {
                    this.mSimpleTestsParams = new SimpleTestsParams();
                }
                return this.mSimpleTestsParams;
            }
        }
        
        public virtual SimpleTests2Params SimpleTests2Params
        {
            get
            {
                if ((this.mSimpleTests2Params == null))
                {
                    this.mSimpleTests2Params = new SimpleTests2Params();
                }
                return this.mSimpleTests2Params;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private SimpleTestsParams mSimpleTestsParams;
        
        private SimpleTests2Params mSimpleTests2Params;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SimpleTests'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class SimpleTestsParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
        /// </summary>
        public string UIMainWindowWindowExePath = "C:\\Users\\nthor\\source\\repos\\SimpleWPFapp\\SimpleWPFapp\\bin\\Debug\\SimpleWPFapp.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
        /// </summary>
        public string UIMainWindowWindowAlternateExePath = "%USERPROFILE%\\source\\repos\\SimpleWPFapp\\SimpleWPFapp\\bin\\Debug\\SimpleWPFapp.exe";
        
        /// <summary>
        /// Select 'CheckBox' check box
        /// </summary>
        public bool UICheckBoxCheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SimpleTests2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class SimpleTests2Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
        /// </summary>
        public string UIMainWindowWindowExePath = "C:\\Users\\nthor\\source\\repos\\SimpleWPFapp\\SimpleWPFapp\\bin\\Debug\\SimpleWPFapp.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\source\repos\SimpleWPFapp\SimpleWPFapp\bin\Debug\SimpleWPFapp.exe'
        /// </summary>
        public string UIMainWindowWindowAlternateExePath = "%USERPROFILE%\\source\\repos\\SimpleWPFapp\\SimpleWPFapp\\bin\\Debug\\SimpleWPFapp.exe";
        
        /// <summary>
        /// Select 'CheckBox' check box
        /// </summary>
        public bool UICheckBoxCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "buttonA";
                    this.mUIStartButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        
        public WpfCheckBox UICheckBoxCheckBox
        {
            get
            {
                if ((this.mUICheckBoxCheckBox == null))
                {
                    this.mUICheckBoxCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUICheckBoxCheckBox.SearchProperties[WpfCheckBox.PropertyNames.AutomationId] = "checkBox1";
                    this.mUICheckBoxCheckBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICheckBoxCheckBox;
            }
        }
        
        public WpfButton UIStartbuttonA
        {
            get
            {
                if ((this.mUIStartbuttonA == null))
                {
                    this.mUIStartbuttonA = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartbuttonA.SearchProperties[WpfButton.PropertyNames.AutomationId] = "buttonA";
                    this.mUIStartbuttonA.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIStartbuttonA;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIStartButton;
        
        private WpfCheckBox mUICheckBoxCheckBox;
        
        private WpfButton mUIStartbuttonA;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
